### ISSUE TITLE
Suspicious "head" forms

### ISSUE THREAD

**Issue by cacfd3a** [jhellingman/phildict#1]
Hello,

I've a view that lists all normalized heads for entries in the Wolff dictionary, extracted from the SQL table that is supplied with the Android app.

I don't really understand the linguistic meaning of "head" in this context, but it seems to be the expanded version of the different word forms that are presented in abbreviated form in the dictionary?

From this understanding, I've noticed a number of strange heads:

|url|normalized head|
|---|---|
|[isa-7660](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/isa-7660)||
|[rpsarpiis-15608](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/rpsarpiis-15608)||
|[a-3](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/a-3)|-a|
|[a-4](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/a-4)|-a(←)|
|[an1-821](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/an1-821)|-an|
|[an2-822](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/an2-822)|-an|
|[an3-823](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/an3-823)|-an|
|[an4-824](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/an4-824)|-an|
|[an-826](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/an-826)|-an-|
|[an-825](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/an-825)|-an(→)|
|[anan1-841](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/anan1-841)|-anan|
|[anan2-842](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/anan2-842)|-anan(→)|
|[anay-858](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/anay-858)|-anay|
|[anun-1021](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/anun-1021)|-anun|
|[ay1-1470](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/ay1-1470)|-ay|
|[ay2-1471](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/ay2-1471)|-ay|
|[g-5025](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/g-5025)|-g-|
|[i-6972](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/i-6972)|-i|
|[i-6973](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/i-6973)|-i(→)|
|[in1-7349](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/in1-7349)|-in-|
|[in2-7350](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/in2-7350)|-in-|
|[in3-7351](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/in3-7351)|-in-|
|[inan-7356](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/inan-7356)|-in-an|
|[inan-7357](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/inan-7357)|-in-an(→)|
|[inanan-7358](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/inanan-7358)|-in-anan|
|[inay-7368](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/inay-7368)|-in-ay|
|[ira-7608](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/ira-7608)|-ira|
|[iru-7653](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/iru-7653)|-iru|
|[lan-10754](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/lan-10754)|-l-an|
|[lun-11729](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/lun-11729)|-l-un|
|[nun-13062](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/nun-13062)|-nun|
|[umr-20220](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/umr-20220)|-um-r-|
|[un1-20230](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/un1-20230)|-un|
|[un2-20231](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/un2-20231)|-un|
|[un-20232](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/un-20232)|-un(→)|
|[unun-20319](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/unun-20319)|-unun|
|[lalim-10652](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/lalim-10652)|-y or nga|
|[bistu-2955](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/bistu-2955)|— ang baraha|
|[ayu-1500](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/ayu-1500)|— nga bata|
|[biking2pawdir-2730](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/biking2pawdir-2730)|— pawdir|
|[bantay-2258](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/bantay-2258)|— sa balutbut|
|[kigul-9135](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/kigul-9135)|(sa) imung kigul|
|[hitsura-6582](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/hitsura-6582)|(walay) hitsura|
|[usab-20454](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/usab-20454)|[adj.] —|
|[pa1-13104](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/pa1-13104)|[adj.] pay [subject]|
|[ra-15309](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/ra-15309)|[adj.] ra|
|[uyamut-20566](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/uyamut-20566)|[adj.] uyamut|
|[para1-13670](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/para1-13670)|[dat.]|
|[uban-19931](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/uban-19931)|[dat.]|
|[usab-20454](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/usab-20454)|[exclamation] usab|
|[lamang-10661](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/lamang-10661)|[expression of time] lamang|
|[pa1-13104](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/pa1-13104)|[future verb abstract form] pa|
|[sir-17024](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/sir-17024)|[gen.] sir|
|[ingun1-7448](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/ingun1-7448)|[maingun|
|[kwadrada-10288](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/kwadrada-10288)|[measurement] kwadrada|
|[sanglay2-16291](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/sanglay2-16291)|[name] nga sanglay|
|[pati1angnounnom-13891](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/pati1angnounnom-13891)|[nom.]|
|[nga-12894](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/nga-12894)|[noun] nga [noun]|
|[pa1-13104](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/pa1-13104)|[noun] pay|
|[pa1-13104](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/pa1-13104)|[noun] pay aku|
|[ikaw-7112](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/ikaw-7112)|[noun] pay imu|
|[sintral-16953](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/sintral-16953)|[noun] sintral|
|[uruy-20448](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/uruy-20448)|[noun]-a ba uruy|
|[tudlu-19417](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/tudlu-19417)|[numeral] ka tudlu|
|[tuud-21711](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/tuud-21711)|[plant name] nga tuud|
|[pa1-13104](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/pa1-13104)|[predicate] pay imu|
|[ra-15309](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/ra-15309)|[preposed gen. pronoun] ra|
|[lamang-10661](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/lamang-10661)|[pronoun|
|[hangtud-6046](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/hangtud-6046)|[pronoun]|
|[irmanus-7641](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/irmanus-7641)|[proper name] irmanus|
|[tunga-19688](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/tunga-19688)|[so-and-so] sa imung (iyang) tunga|
|[unya-20335](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/unya-20335)|[verb base|
|[haskan-6167](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/haskan-6167)|[verb]|
|[labi-10397](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/labi-10397)|[verb]|
|[ki-9104](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/ki-9104)|[verb] ki [verb]|
|[putung-15215](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/putung-15215)|[verb] lang ug putung|
|[kami-8505](https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_show/html/kami-8505)|[verb] ug amu|

The above table is generated using the following query, basically the lexicographic sort of all heads before "a":
https://publicdomainreview.cloudant.com/cebuano_dictionary/_design/show/_view/heads?reduce=false&endkey=%22a%22&inclusive_end=false

Thanks for all this great work!

**Comment by jhellingman** [comment]
Went through the forms; fixed a few forms that where not yet expanded. Note that most of the forms listed here are special, and intentionally include those bracketed forms.
